services:
  # Rust Axum web application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudflare-tunnel-example:latest
    container_name: cloudflare-tunnel-app
    restart: unless-stopped
    networks:
      - tunnel-network
    # No port exposure - only accessible through tunnel
    # ports:
    #   - "8080:8080"
    environment:
      - RUST_LOG=info
    # Health check removed - distroless containers don't have shell utilities
    # We'll use a startup delay instead

  # Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: on-failure
    command: tunnel run
    networks:
      - tunnel-network
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml:ro
      - ./cloudflared/credentials:/etc/cloudflared/credentials:ro
      - ./cloudflared/cert.pem:/home/nonroot/.cloudflared/cert.pem:ro
    environment:
      - TUNNEL_CONFIG=/etc/cloudflared/config.yml
    depends_on:
      app:
        condition: service_started
    deploy:
      restart_policy:
        delay: 10s

networks:
  tunnel-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16