# Cloudflare Tunnel configuration
# This file defines how cloudflared routes traffic to your services

# Tunnel credentials will be mounted from ./credentials/
tunnel: 1e83bc01-0938-41cb-b347-2d331d3bc120
credentials-file: /etc/cloudflared/credentials/1e83bc01-0938-41cb-b347-2d331d3bc120.json

# Ingress rules define how to route traffic
ingress:
  # Main application route - handles both / and /health
  - hostname: halibut.cc
    service: http://app:8080
    originRequest:
      # Disable TLS verification for internal communication
      noTLSVerify: true
      # Set timeout for requests
      connectTimeout: 30s
      # Keep connections alive
      keepAliveConnections: 10
      keepAliveTimeout: 30s
  
  # Catch-all rule (required)
  - service: http_status:404