# Cloudflare Tunnel configuration
# This file defines how cloudflared routes traffic to your services

# Tunnel credentials will be mounted from ./credentials/
tunnel: 90b6148f-e83f-4749-8649-a1cad20715aa
credentials-file: /etc/cloudflared/credentials/90b6148f-e83f-4749-8649-a1cad20715aa.json

# Ingress rules define how to route traffic
ingress:
  # Main application route
  - hostname: hello.halibut.cc
    service: http://app:8080
    originRequest:
      # Disable TLS verification for internal communication
      noTLSVerify: true
      # Set timeout for requests
      connectTimeout: 30s
      # Keep connections alive
      keepAliveConnections: 10
      keepAliveTimeout: 30s
  
  # Health check endpoint (optional subdomain)
  - hostname: health.halibut.cc
    service: http://app:8080
    originRequest:
      noTLSVerify: true
  
  # Catch-all rule (required)
  - service: http_status:404